using System.Text;
using ForgeDesk.Core.Analysis;
using ForgeDesk.Core.Tests.Infrastructure;

namespace ForgeDesk.Core.Tests.Analysis;

public sealed class SourceScannerTests : IDisposable
{
    private readonly TempDirectory _dir = new("source");
    private readonly List<ProjectFile> _files = [];

    private static CancellationToken Ct => TestContext.Current.CancellationToken;

    public void Dispose() => _dir.Dispose();

    [Fact]
    public async Task Counts_lines_per_language_with_colors()
    {
        Add("src/app.ts", "const a = 1;\nconst b = 2;\nexport { a, b };\n");
        Add("src/util.ts", "export const x = 1;");
        Add("tools/run.py", "print('hi')\r\nprint('bye')\r\n");
        Add("README.md", "# Title\n\ntext\n");
        Add("config.json", "{ \"a\": 1 }\n");

        var result = await ScanAsync();

        result.Languages.Should().Equal(
            new LanguageStat("TypeScript", 2, 4, _files[0].Bytes + _files[1].Bytes, "#3178c6"),
            new LanguageStat("Python", 1, 2, _files[2].Bytes, "#3572A5"));
        result.TotalLines.Should().Be(6);
        result.Truncated.Should().BeFalse();
    }

    [Fact]
    public async Task Collects_todos_with_line_numbers()
    {
        Add("src/a.cs", "class A\n{\n    // TODO: split this class\n    void M() { } // FIXME leaks\n}\n");
        Add("script.sh", "#!/bin/sh\n# HACK: sleep until the port is open\nsleep 1\n");

        var result = await ScanAsync();

        result.Todos.Should().Equal(
            new TodoItem("script.sh", 2, "HACK", "sleep until the port is open"),
            new TodoItem("src/a.cs", 3, "TODO", "split this class"),
            new TodoItem("src/a.cs", 4, "FIXME", "leaks"));
        result.TodoCount.Should().Be(3);
    }

    [Fact]
    public async Task Keeps_the_first_500_todos_but_counts_them_all()
    {
        Add("big.js", string.Concat(Enumerable.Range(0, 700).Select(i => $"// TODO item {i}\n")));

        var result = await ScanAsync();

        result.TodoCount.Should().Be(700);
        result.Todos.Should().HaveCount(AnalysisLimits.MaxTodoItems);
        result.Todos[^1].Line.Should().Be(AnalysisLimits.MaxTodoItems);
    }

    [Fact]
    public async Task Skips_binary_minified_generated_vendored_and_lock_files()
    {
        Add("src/real.js", "let a = 1;\n");
        AddBytes("src/binary.js", [0x6C, 0x65, 0x74, 0x00, 0x01, 0x02]);
        Add("src/bundle.js", string.Concat(Enumerable.Repeat("var a=1;", 1000)));
        Add("src/lib.min.js", "var a=1;\n");
        Add("src/Form.Designer.cs", "partial class Form { }\n");
        Add("src/Api.g.cs", "class Api { }\n");
        Add("src/gen.cs", "// <auto-generated>\n// This code was generated by a tool.\nclass Gen { }\n");
        Add("api/service.pb.go", "package api\n");
        Add("vendor/github.com/x/y.go", "package y\n");
        Add("third_party/lib.c", "int x;\n");
        Add("Cargo.lock", "# lock\n");

        var result = await ScanAsync();

        result.Languages.Should().ContainSingle().Which.Should().Be(new LanguageStat("JavaScript", 1, 1, 11, "#f1e05a"));
    }

    [Fact]
    public async Task Skips_files_larger_than_one_megabyte()
    {
        Add("small.go", "package main\n");
        _files.Add(new ProjectFile("huge.go", AnalysisLimits.MaxSourceFileBytes + 1));

        var result = await ScanAsync();

        result.Languages.Single().Files.Should().Be(1);
    }

    [Fact]
    public async Task Decodes_utf16_and_utf8_bom_files()
    {
        AddBytes("utf16.cs", [.. Encoding.Unicode.GetPreamble(), .. Encoding.Unicode.GetBytes("// TODO: wide\nclass A { }\n")]);
        AddBytes("bom.cs", [.. Encoding.UTF8.GetPreamble(), .. Encoding.UTF8.GetBytes("class B { }\n")]);

        var result = await ScanAsync();

        result.TotalLines.Should().Be(3);
        result.Todos.Should().ContainSingle().Which.Text.Should().Be("wide");
    }

    [Fact]
    public async Task Stops_after_the_file_budget_and_reports_truncation()
    {
        for (var i = 0; i < 5; i++)
        {
            Add($"f{i}.rs", "fn main() {}\n");
        }

        var result = await SourceScanner.ScanAsync(_dir.Path, _files, null, Ct, maxFiles: 3);

        result.Truncated.Should().BeTrue();
        result.Languages.Single().Files.Should().Be(3);
    }

    [Fact]
    public async Task Stops_after_the_byte_budget_and_reports_truncation()
    {
        Add("a.rs", new string('/', 60) + "\n");
        Add("b.rs", new string('/', 60) + "\n");

        var result = await SourceScanner.ScanAsync(_dir.Path, _files, null, Ct, maxBytes: 100);

        result.Truncated.Should().BeTrue();
        result.Languages.Single().Files.Should().Be(1);
    }

    [Fact]
    public async Task Reports_progress_and_honors_cancellation()
    {
        // The same small file listed 1 000 times: enough to reach the progress interval without creating 1 000 files.
        _dir.WriteFile("f.c", string.Empty);
        _files.AddRange(Enumerable.Repeat(new ProjectFile("f.c", 0), 1000));

        var messages = new List<string>();
        await SourceScanner.ScanAsync(_dir.Path, _files, messages.Add, Ct);
        messages.Should().Equal("Counting lines of code (1,000 files)…");

        using var cts = new CancellationTokenSource();
        await cts.CancelAsync();
        var act = () => SourceScanner.ScanAsync(_dir.Path, _files, null, cts.Token);
        await act.Should().ThrowAsync<OperationCanceledException>();
    }

    [Theory]
    [InlineData("src/app.min.js", true)]
    [InlineData("package-lock.json", true)]
    [InlineData("deps/go.sum", true)]
    [InlineData("vendor/a.go", true)]
    [InlineData("pkg/vendor/b.go", true)]
    [InlineData("src/Views/Main.xaml.cs", false)]
    [InlineData("src/vendors.ts", false)]
    public void Recognizes_files_to_skip_by_name(string path, bool expected) =>
        SourceScanner.IsSkippedByName(path).Should().Be(expected);

    private void Add(string relativePath, string content)
    {
        var full = _dir.WriteFile(relativePath, content);
        _files.Add(new ProjectFile(relativePath, new FileInfo(full).Length));
    }

    private void AddBytes(string relativePath, byte[] content)
    {
        var full = _dir.WriteFile(relativePath, string.Empty);
        File.WriteAllBytes(full, content);
        _files.Add(new ProjectFile(relativePath, content.Length));
    }

    private Task<SourceScanResult> ScanAsync() => SourceScanner.ScanAsync(_dir.Path, _files, null, Ct);
}
