using System.Globalization;
using System.Text;
using ForgeDesk.Core.Common;

namespace ForgeDesk.Core.Analysis;

internal sealed record SourceScanResult(
    IReadOnlyList<LanguageStat> Languages,
    long TotalLines,
    IReadOnlyList<TodoItem> Todos,
    int TodoCount,
    bool Truncated);

/// <summary>
/// Counts lines per language and collects TODO markers, reading only hand-written source:
/// binary, minified, generated, vendored and lock files are skipped, and reading stops after
/// <see cref="AnalysisLimits.MaxCountedFiles"/> files or <see cref="AnalysisLimits.MaxBytesRead"/> bytes.
/// </summary>
internal static class SourceScanner
{
    private const int ProgressEvery = 1000;
    private const int BinarySniffBytes = 8000;

    private static readonly HashSet<string> LockFiles = new(StringComparer.OrdinalIgnoreCase)
    {
        "package-lock.json", "npm-shrinkwrap.json", "yarn.lock", "pnpm-lock.yaml", "bun.lock", "bun.lockb", "Cargo.lock",
        "poetry.lock", "Pipfile.lock", "uv.lock", "pdm.lock", "composer.lock", "Gemfile.lock", "go.sum", "packages.lock.json",
        "flake.lock", "mix.lock", "pubspec.lock", "Podfile.lock", "gradle.lockfile",
    };

    private static readonly string[] GeneratedSuffixes =
    [
        ".g.cs", ".g.i.cs", ".designer.cs", ".generated.cs", "_pb2.py", "_pb2_grpc.py", ".pb.go", ".pb.cc", ".pb.h", "_generated.go",
        ".min.js", ".min.css", ".min.mjs",
    ];

    private static readonly HashSet<string> VendoredFolders = new(StringComparer.OrdinalIgnoreCase) { "vendor", "third_party", "thirdparty", "3rdparty" };

    private static readonly string[] GeneratedMarkers = ["<auto-generated", "@generated", "Code generated", "DO NOT EDIT"];

    public static async Task<SourceScanResult> ScanAsync(
        string root,
        IReadOnlyList<ProjectFile> files,
        Action<string>? progress,
        CancellationToken cancellationToken,
        int maxFiles = AnalysisLimits.MaxCountedFiles,
        long maxBytes = AnalysisLimits.MaxBytesRead)
    {
        var stats = new Dictionary<string, (LanguageDefinition Language, int Files, long Lines, long Bytes)>(StringComparer.Ordinal);
        var todos = new List<TodoItem>();
        var todoCount = 0;
        var counted = 0;
        long bytesRead = 0;
        var truncated = false;

        foreach (var file in files.OrderBy(f => f.RelativePath, StringComparer.OrdinalIgnoreCase))
        {
            cancellationToken.ThrowIfCancellationRequested();
            var language = LanguageCatalog.Detect(file.RelativePath);
            if (language is null || file.Bytes > AnalysisLimits.MaxSourceFileBytes || IsSkippedByName(file.RelativePath))
            {
                continue;
            }

            if (counted >= maxFiles || bytesRead + file.Bytes > maxBytes)
            {
                truncated = true;
                break;
            }

            var text = await ReadSourceAsync(Path.Combine(root, PathUtil.ToPlatform(file.RelativePath)), cancellationToken).ConfigureAwait(false);
            bytesRead += file.Bytes;
            if (text is null || LooksGenerated(text) || LooksMinified(text))
            {
                continue;
            }

            counted++;
            var lines = CountLinesAndTodos(text, file.RelativePath, language.Comments, todos, ref todoCount);
            stats[language.Name] = stats.TryGetValue(language.Name, out var s)
                ? (language, s.Files + 1, s.Lines + lines, s.Bytes + file.Bytes)
                : (language, 1, lines, file.Bytes);

            if (counted % ProgressEvery == 0)
            {
                progress?.Invoke(string.Create(CultureInfo.InvariantCulture, $"Counting lines of code ({counted:N0} files)…"));
            }
        }

        var languages = stats.Values
            .OrderByDescending(s => s.Lines)
            .ThenByDescending(s => s.Bytes)
            .ThenBy(s => s.Language.Name, StringComparer.Ordinal)
            .Select(s => new LanguageStat(s.Language.Name, s.Files, s.Lines, s.Bytes, s.Language.Color))
            .ToList();
        return new SourceScanResult(languages, languages.Sum(l => l.Lines), todos, todoCount, truncated);
    }

    internal static bool IsSkippedByName(string relativePath)
    {
        var slash = relativePath.LastIndexOf('/');
        var name = slash >= 0 ? relativePath[(slash + 1)..] : relativePath;
        if (LockFiles.Contains(name) || GeneratedSuffixes.Any(s => name.EndsWith(s, StringComparison.OrdinalIgnoreCase)))
        {
            return true;
        }

        return slash > 0 && relativePath[..slash].Split('/').Any(VendoredFolders.Contains);
    }

    internal static bool LooksGenerated(string text)
    {
        var head = text.AsSpan(0, Math.Min(text.Length, 600));
        foreach (var marker in GeneratedMarkers)
        {
            if (head.Contains(marker, StringComparison.Ordinal))
            {
                return true;
            }
        }

        return false;
    }

    /// <summary>Bundled or minified code: a lot of text on very long lines.</summary>
    internal static bool LooksMinified(string text)
    {
        if (text.Length < 4096)
        {
            return false;
        }

        var lines = 1 + text.AsSpan().Count('\n');
        return text.Length / lines > 300;
    }

    /// <summary>Decoded text, or null for unreadable or binary files. Honors UTF-8/UTF-16 byte order marks.</summary>
    internal static async Task<string?> ReadSourceAsync(string path, CancellationToken cancellationToken)
    {
        byte[] bytes;
        try
        {
            bytes = await File.ReadAllBytesAsync(path, cancellationToken).ConfigureAwait(false);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            return null;
        }

        if (bytes.Length >= 2 && ((bytes[0] == 0xFF && bytes[1] == 0xFE) || (bytes[0] == 0xFE && bytes[1] == 0xFF)))
        {
            var encoding = bytes[0] == 0xFF ? Encoding.Unicode : Encoding.BigEndianUnicode;
            return encoding.GetString(bytes, 2, bytes.Length - 2);
        }

        if (bytes.AsSpan(0, Math.Min(bytes.Length, BinarySniffBytes)).Contains((byte)0))
        {
            return null;
        }

        var offset = bytes.Length >= 3 && bytes[0] == 0xEF && bytes[1] == 0xBB && bytes[2] == 0xBF ? 3 : 0;
        return Encoding.UTF8.GetString(bytes, offset, bytes.Length - offset);
    }

    private static long CountLinesAndTodos(string text, string relativePath, CommentSyntax comments, List<TodoItem> todos, ref int todoCount)
    {
        if (text.Length == 0)
        {
            return 0;
        }

        long lines = 0;
        var start = 0;
        while (start < text.Length)
        {
            var end = text.IndexOf('\n', start);
            var lineEnd = end < 0 ? text.Length : end;
            lines++;

            var line = text.AsSpan(start, lineEnd - start);
            if (comments != CommentSyntax.None && TodoScanner.MayContainMarker(line) && TodoScanner.Match(line.ToString(), comments) is { } marker)
            {
                todoCount++;
                if (todos.Count < AnalysisLimits.MaxTodoItems)
                {
                    todos.Add(new TodoItem(relativePath, (int)lines, marker.Tag, marker.Text));
                }
            }

            if (end < 0)
            {
                break;
            }

            start = end + 1;
        }

        return lines;
    }
}
